# Read about the configuration here:
# http://dev.bukkit.org/server-mods/controlorble/pages/configuration/

config:
    customExpLoss: false
    debug: false
    playerDelevel: true
    virtualEXP: false
    virtualPlayerEXP: false
    virtualBlockEXP: false
    hideVirtualEXPMessage: false
    showTotal: false
    expLossByTotal: false
    expBurn: 0
stopMonsterEXP:
    monsterSpawner: false
multipliers:
    monsterEXP: 1
monster:
    Blaze: 10
    CaveSpider: 10
    Creeper: 10
    Enderman: 10
    EnderDragon: 20000
    Ghast: 10
    Giant: 10
    MagmaCube: 10
    PigZombie: 10
    Silverfish: 10
    Skeleton: 10
    Slime: 10
    Spider: 10
    Wolf: 10
    Zombie: 10
animal:
    Chicken: 1
    Cow: 1
    IronGolem: 0
    Ocelot: 0
    OcelotBaby: 0
    OcelotTame: 0
    OcelotTameBaby: 0
    Pig: 1
    Snowman: 1
    Sheep: 1
    Squid: 1
    tameWolf: 0
expLoss:
    Basic: 10
    Contact: 0
    Drown: 0
    Fire: 0
    Lava: 0
    Lightning: 0
    Starve: 0
    Suicide: 0
    TnT: 0
    Void: 0