name: ${name}
main: com.feildmaster.controlorble.JavaPlugin
version: ${version}
author: feildmaster

commands:
  xp:
    description: Override vanilla xp command
  exp:
    description: View/Change experience
  exp-reload:
    description: Allows reload of exp config
  exp-set:
    description: set experience values in game

permissions:
  orbEnhance.viewExp:
    default: op
    description: Allows players to view the experience of others
  orbEnhance.modifyExp:
    default: op
    description: Allows modification of experience values
  orbEnhance.admin:
    default: op
    description: Allows player to change players experience
  orbEnhance.KeepExp:
    default: false
    description: Allows individual players to keep all experience